### ISSUE TITLE
Lap timer is incorrect

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#14]
![screenshot 2019-01-10 at 8 10 32 am](https://user-images.githubusercontent.com/25832911/50981329-97cae680-14af-11e9-99c9-36db15e1ad60.png)
This isn't too important but it really shouldn't happen

**Comment by ScanuNicco** [comment]
I can add an if statement to check if the variables are the same but this is not a priority

**Comment by zorbulator** [comment]
This is absolutely a terrible way to solve the problem. The problem is
caused by using different variables so the solution is to only use
the lapMSeconds which is correct and have a function to turn it into a
string. There shouldn't really be two variables anyway, lapString is only
used for the timer display so it should stay in the timer function (you
should have taken APCSP we learned about scope)

**Comment by zorbulator** [comment]
This has been fixed for now but could be done better
