### ISSUE TITLE
Track Design

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#16]
This isn't really an issue but this seems like the right place to put it: The track doesn't really look like Venice and it would be more simple to make it look right. Here are some reference images of Venice:

![image](https://user-images.githubusercontent.com/25832911/50982737-b7afd980-14b2-11e9-8b12-d8d655a88708.png)
![image](https://user-images.githubusercontent.com/25832911/50982794-d6ae6b80-14b2-11e9-99c3-4951587c4bf1.png)
![image](https://user-images.githubusercontent.com/25832911/50982812-e1690080-14b2-11e9-85ef-a310a23a77b2.png)

We can see that:

1. Buildings go right up to the water
2. They are all pretty tall
3. They are very rectangular in shape with either flat roofs or "pyramid" roofs but not "triangle" roofs like are currently in the game. 
4. Most of the buildings are connected to each other with only some small gaps between them

Can you try to model the buildings in the track to look more like this by making the buildings taller, connected, close to the edge, and rectangular without having a "triangle roof" or a big chimney like a lot of the current buildings and I can texture it to look good even if it's just a bunch of cubes booleaned to the track. Also, if you want to you can make a hitbox for the boat and track. You can even use disconnected edges and loose faces and other things you like because that would save polygons and it doesn't need to be rendered.

**Comment by ScanuNicco** [comment]
I think if fixed this one too

**Comment by zorbulator** [comment]
the roofs still arent fiXed

On Jan 12, 2019 3:08 PM, "scanunicco" <notifications@github.com> wrote:

I think if fixed this one too

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ScanuNicco/Boat-Race/issues/16#issuecomment-453787987>,
or mute the thread
