### ISSUE TITLE
Low FPS on track 2

### ISSUE THREAD

**Issue by ScanuNicco** [ScanuNicco/Boat-Race#19]
I think that this is being caused by doing collisions on the track instead of the hitbox. I could solve this by making the hitbox the first object in the file but I don't know how to do that.

**Comment by ScanuNicco** [comment]
I have already tried moving the objects around in the OBJ file using a text editor but that just messes stuff up more

**Comment by zorbulator** [comment]
If that is the problem, moving them in the top right of the blender view should fix it, and if it doesn't we can try editing the text more or changing the code to find the name "hitbox"

**Comment by ScanuNicco** [comment]
Track 2 no longer has FPS problems, it is track 3 that does, and I am going to try to re make track 3

**Comment by zorbulator** [comment]
Next time close the issue when the problem stops happening please
