### ISSUE TITLE
New tracks

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#20]
Track 3 is very chaotic and not the way it should be because:
1. It isn't like Venice because the roads aren't straight
2. It isn't part of the other tracks (I will make another issue for this)
3. The geometry is too complicated for collision and has rendering problems

The tracks should be more like real race tracks (like those in Assetto Corsa Competizione) where there are some straight parts and turns.

In this image you can see that the track is difficult but still mostly smooth and straight, similar to how our track should be.
![image](https://user-images.githubusercontent.com/25832911/51629510-9c09f180-1efc-11e9-95d3-668ed263a713.png)

**Comment by zorbulator** [comment]
Also, track 2 is pretty much the same difficulty as track 1 because it is just right angle turns, so even if it looks more complicated it is just as easy without shorter parts, more turns, or different turns

**Comment by ScanuNicco** [comment]
Ok, I can make a different track 3

**Comment by zorbulator** [comment]
New track does not have this problem
