### ISSUE TITLE
Game Name

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#22]
The name of this game was recently changed but we can't change the name because the name of the repository is already boat race, and the new name which I can't remember wouldn't be a good name because it is hard to remember, and it doesn't even mean anything.

**Comment by ScanuNicco** [comment]
I can understand that you don't like the new name, but boat race is too generic, we need something else

**Comment by zorbulator** [comment]
I kind of like boat race, and no other game is called boat race and people
aren't going to find our game on google anyway, but a different name would
be fine with me as long as it is memorable, in english, and makes sense.

**Comment by zorbulator** [comment]
Name was changed back
