### ISSUE TITLE
"dev" blend files

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#26]
Please remove these NOW. They get in the way and are completely not needed, I already told you to remove them and now you made more and now it's an even bigger problem. We don't need a dev version because the blend file is always a dev version.

**Comment by ScanuNicco** [comment]
If the only version of the track is the version where everything is the same object then it would be really hard to edit. Instead I have the dev blend files where things are separate so things are easier to change. Once I have changed something I export the track to the non dev file and join everything

**Comment by zorbulator** [comment]
This does not solve the problem. I don't see why the objects need to be separate but if you want to keep the separate objects and have them not get in the way just put them in another layer, not another file.

**Comment by zorbulator** [comment]
We are using a different file now so just remember don't make any new dev files
