### ISSUE TITLE
Can't start game

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#3]
Clicking does not start the game before or after the countdown.

**Comment by ScanuNicco** [comment]
There must be some sort of an error that we can't see because the console is disabled

**Comment by zorbulator** [comment]
controls wasnt defined

**Comment by ScanuNicco** [comment]
I still can't start the game

**Comment by zorbulator** [comment]
I defined controls now but it doesn't run, there is something else causing
problems

**Comment by zorbulator** [comment]
fixed!
