### ISSUE TITLE
Menu open when game starts

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#34]
When the game starts, the player should see the game instead of a disclaimer and a menu. The disclaimer should be in the menu and the menu should start open if we can do that.

**Comment by zorbulator** [comment]
Fixed the disclaimer but the menu is still open. Can this be fixed?

**Comment by ScanuNicco** [comment]
The controls are unlocked by default when the game starts. In Asetto Corsa Competiezone there is a screen that says start race after you have selected your track and car, I could try something like this.

**Comment by ScanuNicco** [comment]
I added a start screen similar to the one in ACC to the game;
