### ISSUE TITLE
Collision is slow when near collidable objects

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#9]
The fps is REALLLY bad when near any objects set to collide. The good way to fix this would be to simplify geometry with hitboxes but if that doesn't work me might need to use a coordinate-based system that would be a pain to use and wouldn't work as well.

To reproduce:

0. Use a version of the game where collision on the bridges is enabled
1. Go near the bridges
2. Go away from the bridges
3. Note the difference in framerate (you won't need a framerate counter, it is obvious)

**Comment by ScanuNicco** [comment]
I am pretty sure the hitbox fixed this
